[build]
  # Build command for the frontend
  command = "cd frontend && npm run build"
  
  # Directory to publish (frontend build output)
  publish = "frontend/dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# SPA redirect rules for React Router
[[redirects]]
  # Redirect all non-asset requests to index.html for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200
  
  # Don't redirect actual files (assets, API calls, etc.)
  force = false

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    # Don't cache the main HTML file
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Custom 404 page (optional)
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404
