name: Backend CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create env file
        run: |
          echo "APP_ENV=ci" >> .env
          echo "DATABASE_URL=sqlite:///../.data/app_data.db" >> .env
          echo "JWT_SECRET=dummy_ci_secret_change_me" >> .env
          echo "JWT_ALGORITHM=HS256" >> .env
          echo "JWT_EXPIRES_MIN=60" >> .env
          echo "ADMIN_EMAIL=ci@example.com" >> .env
          echo "ADMIN_PASSWORD=ChangeMe123!" >> .env
          echo "CORS_ALLOW_ORIGINS=[\"http://localhost:5173\"]" >> .env

      - name: Run Alembic migrations
        run: |
          python -m alembic -c alembic.ini upgrade head

      - name: Lint (ruff)
        run: |
          pip install ruff
          ruff check app || true

      - name: Format check (black)
        run: |
          pip install black
          black --check app || true
